### ISSUE TITLE
Feedback about the WACZ format

### ISSUE THREAD

**Issue by whalehub** [webrecorder/web-archive-collection-format#3]
My own use case for this format involves making large, multi-GB WARC files available for users to browse in their web browser without them having to download the entire archive first.

I first used the command line tool [cdjx-indexer](https://github.com/webrecorder/cdxj-indexer) to create a .cdjx file for an existing 2GB WARC file. Next, I sorted the files into the corresponding folders, created a .zip file out of them, renamed the resulting file to .wacz and finally self-hosted my own instance of ReplayWeb.page that is pointing at a web server which is hosting the .wacz file.

I'm honestly blown away by how well this technology works and by how seamless the whole process was. The index loads quickly and browsing the archive is very snappy, almost on par with browsing the original website.

This is revolutionary stuff! 🚀

**Comment by ikreymer** [comment]
Thanks for the great feedback! Glad to hear its been useful!
Yes, the idea is to make it easier to exchange web archives and also load large web archives on-demand.
I'm planning to make tools to simplify the creation of WACZ into one or two step process, including creating a compressed index! Will let you know when they're ready!

**Comment by whalehub** [comment]
@ikreymer It this the tool you were referring to? <https://github.com/webrecorder/wacz-format/tree/master/py-wacz>

**Comment by ikreymer** [comment]
Yes :) Still in early development, hope to make it ready for initial release soon!
